<a href="https://colab.research.google.com/github/mrrajatgarg/electrical_machine_learning/blob/master/electrical_classification_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#https://drive.google.com/open?id=0ByRlxZxb6TEVaGgzVWRUbVAwb205SjNjSnYzOE5FeVE1Nmtr

In [0]:
# Install the PyDrive wrapper & import libraries.
# This only needs to be done once in a notebook.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

    100% |████████████████████████████████| 993kB 10.0MB/s 


In [0]:
# Authenticate and create the PyDrive client.
# This only needs to be done once in a notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:

link = 'https://drive.google.com/open?id=0ByRlxZxb6TEVaGgzVWRUbVAwb205SjNjSnYzOE5FeVE1Nmtr'

fluff, id = link.split('=')

print (id) # Verify that you have everything after '='

downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('WPTFeatures254_FaultStates_classnumer.xlsx')

0ByRlxZxb6TEVaGgzVWRUbVAwb205SjNjSnYzOE5FeVE1Nmtr


In [0]:
import pandas as pd

In [0]:
whole_dataset = pd.read_excel('WPTFeatures254_FaultStates_classnumer.xlsx')

In [0]:
whole_dataset.head()

F1       F2      F3      F4       F5       F6      F7      F8      F9  \
0  1861.7  0.54780  1825.1  36.810  0.36316  0.18484  1628.0  197.40  1.1270   
1  2176.0  0.46782  2145.9  30.157  0.29926  0.16862  1957.6  188.37  1.1587   
2  2660.6  0.59622  2624.1  36.672  0.37282  0.22341  2403.5  220.93  1.4142   
3  3037.9  0.58387  3001.8  36.357  0.36652  0.21736  2781.3  220.97  1.3562   
4  2221.1  0.39650  2196.9  24.278  0.24262  0.15393  2045.5  151.58  1.0589   

      F10  ...        F246      F247      F248      F249      F250      F251  \
0  35.704  ...    0.019253  0.001279  0.000637  0.001001  0.000630  0.004361   
1  29.002  ...    0.011436  0.000862  0.000607  0.000830  0.000722  0.006171   
2  35.260  ...    0.011709  0.001056  0.000894  0.001159  0.000915  0.005991   
3  35.002  ...    0.011237  0.001237  0.001174  0.001061  0.000815  0.005821   
4  23.222  ...    0.009779  0.001043  0.000823  0.000839  0.000727  0.003275   

       F252      F253      F254  class  
0  0.004167  0.001329  0.002935      1  
1  0.004248  0.001130  0.002683      1  
2  0.006243  0.001617  0.002562      1  
3  0.005994  0.001551  0.003362      1  
4  0.003836  0.001229  0.002445      1  

[5 rows x 255 columns]

# Importing Libraries

In [0]:
import numpy as np
import pandas as pd

In [0]:
from keras.utils.np_utils import to_categorical

from keras.models import Sequential

from sklearn.utils import shuffle

Using TensorFlow backend.


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
from keras.models import Sequential

from keras.layers import Dense

from keras.layers import BatchNormalization

# Creating dataset into dataset and labels

In [0]:
labels = whole_dataset['class']

In [0]:
labels.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

In [0]:
raw_data = whole_dataset.drop(['class'], axis=1)

In [0]:
raw_data.head()

F1       F2      F3      F4       F5       F6      F7      F8      F9  \
0  1861.7  0.54780  1825.1  36.810  0.36316  0.18484  1628.0  197.40  1.1270   
1  2176.0  0.46782  2145.9  30.157  0.29926  0.16862  1957.6  188.37  1.1587   
2  2660.6  0.59622  2624.1  36.672  0.37282  0.22341  2403.5  220.93  1.4142   
3  3037.9  0.58387  3001.8  36.357  0.36652  0.21736  2781.3  220.97  1.3562   
4  2221.1  0.39650  2196.9  24.278  0.24262  0.15393  2045.5  151.58  1.0589   

      F10    ...         F245      F246      F247      F248      F249  \
0  35.704    ...     0.022249  0.019253  0.001279  0.000637  0.001001   
1  29.002    ...     0.014066  0.011436  0.000862  0.000607  0.000830   
2  35.260    ...     0.018537  0.011709  0.001056  0.000894  0.001159   
3  35.002    ...     0.017570  0.011237  0.001237  0.001174  0.001061   
4  23.222    ...     0.012535  0.009779  0.001043  0.000823  0.000839   

       F250      F251      F252      F253      F254  
0  0.000630  0.004361  0.004167  0.001329  0.002935  
1  0.000722  0.006171  0.004248  0.001130  0.002683  
2  0.000915  0.005991  0.006243  0.001617  0.002562  
3  0.000815  0.005821  0.005994  0.001551  0.003362  
4  0.000727  0.003275  0.003836  0.001229  0.002445  

[5 rows x 254 columns]

# Converting into numpy array and convering labels to one-hot representation

In [0]:
raw_data_numpy = raw_data.values

labels_numpy = labels.values

In [0]:
print(raw_data_numpy.shape)

print(labels_numpy.shape)

(1800, 254)
(1800,)


In [29]:
labels_numpy_new = labels_numpy - 1
print(labels_numpy_new[0:5])

[0 0 0 0 0]


In [0]:
labels_one_hot = to_categorical(labels_numpy_new)

In [31]:
print(labels_one_hot[0:5])
print(labels_one_hot.shape)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]
(1800, 8)


In [0]:
final_dataset, final_labels = shuffle(raw_data_numpy, labels_one_hot)

In [33]:
print(final_dataset.shape)
print(final_labels.shape)
print(final_dataset[0:5])
print(final_labels[0:5])

(1800, 254)
(1800, 8)
[[2.9764e+03 3.0611e-01 2.9568e+03 ... 3.8865e-03 3.5460e-03 2.8321e-03]
 [3.2036e+03 8.2730e-01 3.1555e+03 ... 5.0758e-03 2.2950e-03 3.3904e-03]
 [1.9159e+03 2.5872e-01 1.8987e+03 ... 2.2173e-03 6.4801e-04 1.6041e-03]
 [3.2811e+03 9.7070e-01 3.2225e+03 ... 9.2519e-03 8.8207e-03 6.7108e-03]
 [3.1584e+03 3.4976e-01 3.1360e+03 ... 3.8551e-03 2.9828e-03 2.8587e-03]]
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


# Splitting the dataset into train test split

Training = 80%

Test = 20%

In [0]:
X_train, X_val, y_train, y_val = train_test_split(final_dataset, final_labels, test_size=0.2, random_state=1)

In [37]:
print(X_train.shape)
print(y_train.shape)

(1440, 254)
(1440, 8)


In [38]:
print(X_val.shape)
print(y_val.shape)

(360, 254)
(360, 8)


In [43]:
input_shape = X_train.shape[1]

print(input_shape)

254


# Creation of model

In [0]:
model = Sequential()

model.add(BatchNormalization(input_shape = (254,)))

model.add(Dense(units = 8, activation = 'sigmoid'))

#model.add(Dense(units = 8, activation = 'sigmoid'))

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [58]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
batch_normalization_3 (Batch (None, 254)               1016      
_________________________________________________________________
dense_7 (Dense)              (None, 8)                 2040      
Total params: 3,056
Trainable params: 2,548
Non-trainable params: 508
_________________________________________________________________


In [59]:
model.fit(X_train, y_train, validation_data = (X_val, y_val), epochs = 30, batch_size = 64)

Train on 1440 samples, validate on 360 samples
Epoch 1/30
1440/1440 [==============================] - 1s 857us/step - loss: 1.8450 - acc: 0.4229 - val_loss: 1.6233 - val_acc: 0.5389
Epoch 2/30
1440/1440 [==============================] - 1s 409us/step - loss: 1.5267 - acc: 0.5708 - val_loss: 1.4321 - val_acc: 0.6389
Epoch 3/30
1440/1440 [==============================] - 0s 308us/step - loss: 1.3667 - acc: 0.6556 - val_loss: 1.2995 - val_acc: 0.6972
Epoch 4/30
1440/1440 [==============================] - 0s 311us/step - loss: 1.2343 - acc: 0.7146 - val_loss: 1.1525 - val_acc: 0.7611
Epoch 5/30
1440/1440 [==============================] - 1s 398us/step - loss: 1.0707 - acc: 0.7347 - val_loss: 0.9636 - val_acc: 0.7111
Epoch 6/30
1440/1440 [==============================] - 0s 293us/step - loss: 0.8722 - acc: 0.7583 - val_loss: 0.7560 - val_acc: 0.7861
Epoch 7/30
1440/1440 [==============================] - 1s 389us/step - loss: 0.6702 - acc: 0.8639 - val_loss: 0.5594 - val_acc: 0.9167
E

In [0]:
model.save('electrical_classification_model.h5')

In [0]:
# Install the PyDrive wrapper & import libraries.
# This only needs to be done once in a notebook.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
# Authenticate and create the PyDrive client.
# This only needs to be done once in a notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [91]:
# Create & upload a file.
uploaded = drive.CreateFile({'title': 'electrical_classification_model.h5'})
uploaded.SetContentFile('electrical_classification_model.h5')
uploaded.Upload()
print('Uploaded file with ID {}'.format(uploaded.get('id')))

Uploaded file with ID 1vlM0DdCpMSEAbXzyj5P0ZqSlamOKNCqb


# Loading of model

In [0]:
# Install the PyDrive wrapper & import libraries.
# This only needs to be done once in a notebook.
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [0]:
# Authenticate and create the PyDrive client.
# This only needs to be done once in a notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [101]:

link = 'https://drive.google.com/open?id=1vlM0DdCpMSEAbXzyj5P0ZqSlamOKNCqb'

fluff, id = link.split('=')

print (id) # Verify that you have everything after '='

downloaded = drive.CreateFile({'id':id}) 
downloaded.GetContentFile('electrial_classification_model.h5')

1vlM0DdCpMSEAbXzyj5P0ZqSlamOKNCqb


In [0]:
import keras

model_load = keras.models.load_model('electrical_classification_model.h5')

# Doing Predictions on Test Data

In [0]:
sample_number = 7

In [98]:
test_data_sample = X_val[sample_number].reshape(1, 254)
test_data_actual_label = y_val[sample_number]

print(test_data_sample.shape)
print(test_data_actual_label)

(1, 254)
[0. 0. 0. 0. 0. 0. 1. 0.]


In [0]:
predicted_label = model_load.predict(test_data_sample)

In [100]:
print(np.argmax(predicted_label))

6
